### ISSUE TITLE
[idea] meybe making a ROM

### ISSUE THREAD

**Issue by zapewne** [evansm7/umac#3]
Is possible catch rom function from emulator and write this function in C?
Similar WINE system on Linux and Windows.
Many people not have orginal ROM. 

Second trouble is, how writing a new program? System 3.0 is ok, but not have a language support.
I'm from Poland and I cant use, program in my language. This is trouble. Meybe You can add support other language to this sytem? (probably not, meybe move to 7.0.1) ?

**Comment by og1en** [comment]
Are you able to change the rom or software so that the eject position is not there?
So that it cannot be selected?

Maybe as someone suggested replace the rom file with VM pseudocode or bytecode or C and slowly step by step remove the ROM or system at all to be able to run the program.

The idea is to run one program. But to make it one file too. Let's say let it be an editor. Let it be one program and I will be able to print a letter on a laser printer. I can save the files on my system.

**Comment by evansm7** [comment]
Ha! Both of those are huge projects and I wish someone else luck with them (it won’t be me doing that)! :)

@zapewne have you seen https://www.v68k.org/advanced-mac-substitute/ ? It seems to do exactly that. Re system 7, no, that’s too big to run on this Mac unfortunately. 

I don’t know how to develop apps for 3.2.  Good luck!

**Comment by probonopd** [comment]
Don't know whether it could be ported to the RP2040, but https://github.com/autc04/executor is also a substitute for the Apple ROM that can be configured to just run one application.
